atomicateam/atomica

clients/cascade/src/app/OptimizationsPage.vue, clients/tb/src/app/OptimizationsPage.vue
This PR improves error task processing in the Optimizations page.  Now if a Celery task ends in an error, the Status column will show "Error after [time elapsed]".  Also, the error will show up in the console, although you may have to leave the Optimizations page and scroll back to it to find it.  It remains to clean up polling so that it turns off when there are no optimizations that have task statuses of "queued" or "started".
=> Have task error display working on Optimization pages for TB and Cascade

clients/cascade/src/app/FrameworksPage.vue, clients/cascade/src/app/ProjectsPage.vue, clients/tb/src/app/ProjectsPage.vue
This PR changes the renaming interface of the Projects and Frameworks pages of both apps by letting the user click outside the renaming textbox to complete the renaming.
=> Rename click finish

clients/cascade/src/app/CalibrationPage.vue, clients/tb/src/app/CalibrationPage.vue
This PR, for both the Cascade and TB sites, removes the refresh paramset button in the Calibration (Baseline) pages.  Instead of this button being necessary, changing the dropdown selection updates this, and after deletions or uploads of paramsets are done, it also will do the refresh.
=> Improve parset updating

atomica/programs.py
The program outcomes for the additive+random interaction need to be sorted by delta rather than outcome, so that the most effective program is picked even if the effect of the program is to decrease the parameter value
=> Minor fix for programs

atomica/defaults.py, atomica/plotting.py, atomica/programs.py, atomica/results.py, docs/examples/Plot-Programs.ipynb, docs/general/Programs.rst, requirements.txt, tests/test_malaria.py, tests/test_tox_scenarios.py, tox.ini
This PR 'completes' program scenarios by adding a third scenario type, 'capacity scenarios' in which program capacity is able to be overwritten. Thus program scenarios can be applied at each stage of the program calculation
- Overwrite spending
- Overwrite capacity
- Overwrite fractional coverage
Since there are not expected to be many use cases for capacity scenarios, the low-level functionality in `ProgramInstructions` has been implemented, but a corresponding `Scenario` type has not been defined, so capacity scenarios would need to be run by directly instantiating the appropriate `ProgramInstructions` object. 
Examples of all three scenarios, both as low-level scenarios and via `Scenario` objects (for budget and coverage scenarios) are provided in `test_tox_scenarios.py`
=> Capacity scenarios

atomica/function_parser.py, docs/general/Parameters.rst
The `to_timestep()` and `to_annual()` functions are out of date because the method for scaling probabilities with timestep has changed as per https://docs.atomica.tools/en/master/examples/Probability-Rescaling.html. As the new method involves straight multiplication and division, it is cleaner to write them explicitly rather than using these functions, so these can be deprecated
=> Deprecate functions

atomica/plotting.py, atomica/programs.py, tests/test_plot_programs.py
Currencies are currently partially supported in Atomica - `ProgramSet` objects contain currencies, but they were not being read in automatically from the progbook or plotted correctly. This PR adds in the remaining features. 
- To write a new progbook with a different currency, pass the `currency` argument to the constructor
- When a progbook is read in, the currency is set based on the spending data sheet, and validated to ensure all quantities are in the same units
- When plotting, the local currency is plotted. The axis label is formatted correctly even if the currency is a string rather than a symbol e.g. 'USD' instead of '$'
=> Add in remaining features to support currencies fully

atomica/framework.py, atomica/model.py, atomica/parameters.py, atomica/results.py, atomica/version.py, docs/examples/Uncertainty.ipynb, setup.py, tox.ini
This PR improves robustness of unit validation between the framework and databook. Specifically, it is now less case and whitespace sensitive, so units like 'number' and 'Number' and 'number ' will all get treated the same for timescale formatting and validation purposes
=> Case fixes

atomica/migration.py, atomica/model.py, atomica/parameters.py, atomica/results.py, atomica/scenarios.py, atomica/version.py, azure-pipelines.yml, requirements.txt, tests/test_tox_calibration.py, tests/test_tox_library.py, tests/test_tox_scenarios.py, tox.ini
This PR lifts the restriction that function parameters cannot be targeted. Originally this was prevented to stop users from violating the parameter functions accidentally - for example, overwriting force of infection rather than overwriting the components that get used to calculate the force of infection.
However, some frameworks use parameters functions to automate conversions from number to probability. The intended usage is for users to complete databooks in number format (e.g. number of diagnoses) but to be able to write program outcomes in probabilities (e.g. probability of diagnosis). Canonically, the databook should be in probability format and users should perform any necessary conversions beforehand - but for some models it's not realistic to expect this of users. Similarly, it …
=> Parscen functions

atomica/plotting.py, atomica/scenarios.py, atomica/utils.py, atomica/version.py, docs/examples/Plot-Programs.ipynb, docs/examples/Plotting.ipynb, tests/test_tox_scenarios.py
This PR makes it so that parameter scenarios now do not end by default. A flag is provided in the scenario values. If `False` (default) then the last scenario value is used until the end of the simulation, whenever that is. If `True`, the scenario ends immediately after the last scenario value, which was previously the default behaviour.
To improve robustness of this feature and other related interpolations, the `pchip` interpolation has been replaced by linear interpolation throughout. Results may be slightly affected, but not significantly. Some plots may occasionally appear more jagged (but this is typically unlikely because existing normal series plots do not use interpolation anyway). The TB model appears to run about 10% faster
=> Fix parscen inf

atomica/optimization.py, atomica/project.py
This PR updates the optimization variables to use flows instead of compartments for `ddis` and `acj`. In particular, `acj` is always `0` so it had no effect previously, whereas `:acj` (the flow into the active junction) is more appropriate to use
=> Update FE optimization variables

atomica/framework.py, tests/test_tox_scenarios.py
This PR adds extra validation to provide a clearer error message if the user tries to use a population aggregation on flow rates
=> Aggregation validation

atomica/optimization.py
Proposed PR to address issues encountered in application optimization. The root cause of the problem appeared be that when the the initial budget is very close or already satisfactory, the minimization routine would see slow relative improvements (potentially just numerical) that prevent convergence. It's unclear how to appropriately set `ftol` to deal with both small and large budget adjustments. This PR relaxes `ftol` by one order of magnitude. It also increases the number of iterations, as the failing cases were failing after 500 iterations, but only required ~560 to converge. Finally, additional logic has been added to skip the minimization routine entirely if simply rescaling the budget multiplicatively satisfies all individual constraints
=> Optimization numeric adjustments

CHANGELOG.md, atomica/__init__.py, atomica/calibration.py, atomica/framework.py, atomica/optimization.py, atomica/plotting.py, atomica/programs.py, atomica/project.py, atomica/version.py, tests/test_api_workflow.py
This PR mainly tweaks calibration 
- Rename `at.perform_autofit` to `at.calibrate`. This matches the existing `Project.calibrate` method, as well as better aligns with `at.optimize` 
- Improve logging granularity - extra messages are now printed at the `DEBUG` logger level and can be accessed by changing the logger level e.g. `atomica.logger.setLevel(1)`
=> Calibration tweaks

CHANGELOG.md, atomica/model.py, atomica/version.py
This PR fixes an unusual edge case, if a parameter had a function and is targetable but does not directly or indirectly drive any transitions. In that case, the parameter would not be considered dynamic and although programs get evaluated at every timestep, the parameter function would overwrite the program outcomes at the end of integration. This PR makes it so that if a parameter is targeted by the Progset, then it is considered dynamic so that the function is precomputed and the program outcomes are not overwritten
=> Add extra condition for making parameter dynamic based on programs

CHANGELOG.md, atomica/plotting.py, atomica/programs.py, atomica/reconciliation.py, atomica/results.py, atomica/version.py, setup.py
- Replace deprecated ``sc.SItickformatter`` usage
- Fix bug in program coverage overwrite timestep scaling. Coverage overwrites must always be provided in dimensionless units
=> Fix deprecations and coverage

CHANGELOG.md, atomica/plotting.py, atomica/version.py
Updates the plotting code to use `sc.SIticks()`, rather than `sc.SItickformatter()`, which is an internal which wasn't intended to be used directly. For compatibility with Sciris >=1.2.1. But should be fully backwards compatible, too.
=> Update SIticks to use function instead of formatter

atomica/model.py, atomica/parameters.py, atomica/programs.py, atomica/project.py
The trouble was with a ">" residual link.
- `outflow` wasn't updated with the stochastic `outflow_fractions`, and
- The probabilities need to sum to 1 in a multinomial so we give the residual probability to the residual link
Also, this checks that net_inflow is an integer and throws an error if it is not. The other links coming into the ResidualJunctionCompartment should have integer flows when `stochastic = True` but I'm not sure it is appropriate to check this here and throw an error?
=> Fix ResidualJunctionCompartment not applying stochasticity correctly

CHANGELOG.md, atomica/model.py, atomica/version.py
Add information about which parameter or junction is causing an error - with the errors mainly being caused by: ``with np.errstate(all='raise'):``
I went through and found all the uses of ``parse_function()`` where the output function ``fcn`` is then called - which turns out to only be in ``Parameter.update()``
I also went through ``model.py`` and found all divisions without a check for a divide by zero beforehand.
=> Catch model exceptions and add info before re-raising

CHANGELOG.md, atomica/model.py, atomica/parameters.py, atomica/version.py, docs/conf.py
- Improve error message if calibration file contains duplicate entries
- Transfer parameters no longer raise an error if specified in 'Duration' units
- Transfer parameters in rate units are no longer limited to a maximum value of 1
- Some numerical errors in `model.py` (particularly relating to errors/warnings in parameter functions) are now caught and printed with more informative error messages.
=> Allow transfer duration units, improved error handling

CHANGELOG.md, atomica/plotting.py, atomica/project.py, atomica/version.py, tests/test_tox_timed_compartments.py
Fixes a minor bug in project creation where arguments like `sim_start` would be ignored because they were being applied before loading a databook rather than after
=> Project init

CHANGELOG.md, atomica/excel.py, atomica/framework.py, atomica/migration.py, atomica/model.py, atomica/parameters.py, atomica/programs.py, atomica/version.py, tests/text_tox_timed_initialization.py
This PR implements a feature we discussed a while ago - saving initial compartment sizes *including subcompartment sizes for timed compartments* into a `ParameterSet` where they are considered to be part of the calibration. This means that it's possible to actually initialize the model in a steady state respecting the steady state values of the subcompartment. For example
Default initialization
Setting the correct steady state compartment sizes in the databook/via Y-factors (but without setting subcompartment values)
Even though the total steady state values are correct, there is still a small transient because the subcompartments are not at equilibrium. With the new functionality
The transients at the start are now gone. The main functionality is
```
res = P.run_sim(result_name='basic') …
```
=> Timed compartment initialization

CHANGELOG.md, atomica/calibration.py, atomica/version.py
Edit the objective function calculation to allow the Measurables to use total population data ('Total'). 
The total population calculation is calculated using the `PlotData` function.
All four inputs (`measurable, target population, weight, metric`)
Example: 
`cal = P.calibrate(max_time=100, parset=cal, adjustables=['infx'], measurables=[('chronic_total', 'Total', 1.0, 'fractional')])`
=> Total pop calibration

atomica/project.py, tests/test_time_vector.py
Fix simulation time vector:
Problem: When using `np.linspace(2000, 2051-1/12, int(np.float32(((2051-1/12 - 2000) / (1/12)))) + 1))` to generate the time vector, we can convert it to an integer array and return the counts for each year, and we will end up with 12 counts for most years, but 13 counts for year 2038 and 11 counts for 2048 due to numerical imprecision of the step size calculated by `np.linspace`. And this is causing issues in the results. 
This PR is using a different approach (credits to Kelvin!): 
1. Use `arange` with step size of 1 which is exact
2. Use our correct step size and multiply it
3. Add our start time
=> Time vector precision
